MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.14'  # [osx and x86_64]
  - '10.15'  # [osx and arm64]
macos_min_version:  # [osx]
  - '10.14'  # [osx and x86_64]
  - '10.15'  # [osx and arm64]
CONDA_BUILD_SYSROOT:            # [osx and x86_64]
  - /opt/MacOSX10.14.sdk        # [osx and x86_64]

# Use gcc 8 for ppc64le
c_compiler_version:            # [ppc64le]
  - 8                          # [ppc64le]
cxx_compiler_version:          # [ppc64le]
  - 8                          # [ppc64le]

pin_run_as_build:
  # libuv is missing run_exports
  libuv:
    max_pin: x.x
    min_pin: x.x.x
