MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.15'  # [osx and x86_64]
macos_min_version:  # [osx]
  - '10.15'  # [osx and x86_64]
CONDA_BUILD_SYSROOT:            # [osx and x86_64]
  - /opt/MacOSX10.15.sdk        # [osx and x86_64]

pin_run_as_build:
  # libuv is missing run_exports
  libuv:
    max_pin: x.x
    min_pin: x.x.x
