MACOSX_DEPLOYMENT_TARGET:
  - '10.11'  # [osx and x86_64]
macos_min_version:
  - '10.11'  # [osx and x86_64]

pin_run_as_build:
  # libuv is missing run_exports
  libuv:
    max_pin: x.x
    min_pin: x.x.x
