{% set version = "19.0.1" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 93 %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [not win]
  sha256: 6524eb35e1b3c1fc128f9fb6c9ecd92aaba64261fa411aeec6a193019791a51b  # [not win]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: a15925b346cb6906b916c4e18373e3311d921cf4de17b14e041ff238fc9639e0  # [win]
  patches:
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]
    - 0001-Forward-ceilf-floorf.patch  # [not win]
    - 0001-Force-include-handler-outside-simulator.patch  # [osx and arm64]

build:
  number: 0
  # Anaconda doesn't provide nodejs on s390x because it's not included in SOW packages
  skip: True  # [s390x]
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 3.7  # [not (win or (osx and arm64))]
    - python 3.8  # [osx and arm64]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run:
    - vs2015_runtime  # [win]
    - icu  # [not win]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and arm64]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: a platform for easily building fast, scalable network applications
  description: |
    Node.js is an open-source, cross-platform JavaScript runtime environment.
  doc_url: https://nodejs.org/en/docs/
  doc_source_url: https://github.com/nodejs/node/releases
  dev_url: https://nodejs.org/en/docs/guides/
extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
    - katietz
