{% set version = "20.17.0" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 115 %}

package:
  name: nodejs
  version: {{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [unix]
  sha256: 409bda5f1896c7c20866610d778d1760991884ad2e7940837cd3f2854cf73747  # [unix]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: e323fff0aba197090faabd29c4c23f334557ff24454324f0c83faa7e399dbb74  # [win]
  patches:  # [not win]
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]
    - less-shared-intermediate.patch  # [not win]
    - 0001-Forward-ceilf-floorf.patch  # [not win]

build:
  number: 0
  # Anaconda doesn't provide nodejs on s390x because it's not included in SOW packages
  skip: True  # [s390x]
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}    # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 3.8             # [not win]
    - ninja-base             # [not win]
    - pkg-config             # [not win]
    - patch                  # [not win]
    # libuv is a bootstrap dependency in js2c
    # starting with 20.3 (https://github.com/nodejs/node/pull/46997)
    - libuv 1.48
  host:
    - icu {{ icu }}
    # The introduction of the uv_pipe_bind2 and uv_pipe_connect2 methods in
    # libuv v1.46.0 changed the behaviour of uv_pipe_bind and uv_pipe_connect.
    # see https://github.com/nodejs/node/pull/49667 and https://docs.libuv.org/en/v1.x/pipe.html#c.uv_pipe_bind2
    # uv_pipe_bind2 added in v20.8.0 of the 20.x branch
    # https://github.com/nodejs/node/blob/v20.8.0/src/pipe_wrap.cc
    - libuv 1.48             # [not win]
    - openssl {{ openssl }}  # [not win]
    - zlib {{ zlib }}        # [not win]
  run:
    - {{ pin_compatible('icu') }}
    - libuv                  # [not win]
    - openssl                # [not win]
    - zlib                   # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("11.1") }}  # [osx and arm64]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Node.js is an open-source, cross-platform JavaScript runtime environment.
  description: |
    Node.js is an open-source, cross-platform JavaScript runtime environment.
    As an asynchronous event-driven JavaScript runtime, Node.js is designed to
    build scalable network applications.
  doc_url: https://nodejs.org/en/docs/
  dev_url: https://github.com/nodejs/node

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
    - katietz
