{% set version = "6.11.2" %}

package:
  name: nodejs
  version: {{ version }}

source:
  fn: node-v{{ version }}.tar.gz
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz
  sha256: 20146ed51b638404665737ed8a25cc06e96d7d7259eb90a4bdec4730a78002a6

build:
  number: 0
  ignore_prefix_files:
    - bin/node

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # node's build scripts find and use MSVC 2015, regardless of conda's setting.
    - vs2015_runtime  # [win]
    - python          2.7.*
  run:
    - vs2015_runtime   # [win]
    - libgcc           # [linux]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]

about:
  home: https://nodejs.org/
  license: MIT
  summary: a platform for easily building fast, scalable network applications

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
