{% set version = "18.15.0" %}

# NODE_MODULE_VERSION set in src/node_version.h
{% set NODE_MODULE_VERSION = 108 %}

package:
  name: nodejs
  version: {{ version }}

source:
  # checksums from https://nodejs.org/dist/vX.Y.Z/SHASUMS256.txt.asc
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}.tar.gz  # [unix]
  sha256: d65c4c3ef3c8815bccda9502081a29458c7c80797db0763f8752f270a824ac2b  # [unix]
  url: https://nodejs.org/dist/v{{ version }}/node-v{{ version }}-win-x64.zip  # [win]
  sha256: 118fbcae58bc8c53cbe97a10c019734ed90685da8dda98aa0b0f4aeead42a647  # [win]
  patches:  # [not win]
    - linux-librt.patch  # [not win]
    - cinttypes.patch  # [linux]
    - less-shared-intermediate.patch  # [not win]
    - 0001-Forward-ceilf-floorf.patch  # [not win]
    - 0002-ppc64le-remove-const.patch  # [ppc64le]

build:
  number: 1
  # Anaconda doesn't provide nodejs on s390x because it's not included in SOW packages
  skip: True  # [s390x]
  # Prefix replacement breaks in the binary embedded configurations.
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - {{ compiler('cxx') }}  # [not win]
    - python 3.8  # [not win]
    - git  # [linux]
    - ninja  # [not win]
    - pkg-config  # [not win]
    - patch     # [not win]
    - llvm-tools  # [osx]
    - binutils    # [linux]
  host:
    # icu min version is 69. It won't compile without this minumum version.
    # until the distribution gets updated to a new icu, internationalization is disabled. 
    # - icu 58        # [not (win or s390x or aarch64 or (osx and arm64))]
    # - icu 68        # [s390x or aarch64 or (osx and arm64)]
    - libuv 1.44    # [not win]
    - openssl 1.1.1 # [not win]
    - zlib 1.2      # [not win]
  run:
    # icu min version is 69. It won't compile without this minumum version.
    # until the distribution gets updated to a new icu, internationalization is disabled. 
    - icu >=58,<59.0a0        # [not (win or s390x or aarch64 or (osx and arm64))]
    - icu >=68,<69.0a0      # [s390x or aarch64 or (osx and arm64)]
    - libuv  # [not win]
    - openssl  # [not win]
    - zlib  # [not win]
  run_constrained:   # [osx]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}   # [osx and x86_64]
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.15") }}  # [osx and arm64]

test:
  commands:
    - node -h
    - node -v
    - npm version
    - npm install -h
    - npm config get prefix -g
    - test $(echo "console.log(1 + 3)" | node) == 4  # [not win]
    - test -f $PREFIX/lib/libnode.{{ NODE_MODULE_VERSION }}.dylib  # [osx]
    - test -f $PREFIX/lib/libnode.so.{{ NODE_MODULE_VERSION }}  # [linux]

about:
  home: https://nodejs.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Node.js is an open-source, cross-platform JavaScript runtime environment.
  description: |
    Node.js is an open-source, cross-platform JavaScript runtime environment.
    As an asynchronous event-driven JavaScript runtime, Node.js is designed to 
    build scalable network applications.
  doc_url: https://nodejs.org/en/docs/
  dev_url: https://github.com/nodejs/node

extra:
  recipe-maintainers:
    - minrk
    - msarahan
    - pelson
    - blink1073
    - xhochy
    - katietz
