travis:
  secure:
    BINSTAR_TOKEN: a0Z0HAVV8wP1tSi2q+bKlpz4ui6AOG8JufoJYQC6lMDhgAIrgVMQlrDlzFD8EhORwYIN+QgEgRwQJRY7TblvzQIUOK7ipwsBoOV/zC5XqZFrAcpsbEuu7UtzRGxMOj68HVETWWAuOwKHrmyGDH+jvhcGbUy/xXDLanzRgHSLSoraapyou23Z6DjITPAmQH09MEbTh1vcvC7KpgeO1Xfp6wA4N8DCpgyYuib0LH/JE3NrOLWb9G4AXe2GWcYL1U0cTQwWoTsSgd/vKVa6tWJn+yLVO5McCUqjhe2dNuo28IZC1NQr9BIUv6i9yZO09nhi0Fzy5s1rqw+93+g30ysgCNAvNQHbETuV1vTqK3+xjsRewJRZJVL4xh4qo3dSOfiVrdAXQqLSBemxP99jfgf0W9He3HS6Brf1oHEDg70a8MXT8p8UnpmAUynLHW5YIIq20/D/p+Il6EezDuq4N98bjLywwV7GsTL3XEzJXTN36acaRDQ5ep0Y+98DGRBYoA1lTT6o43tBSkDoJyIwyvZgliheE3Q2kwizO+vtYFN55fF/L/nsQgHXNl5lisMu12ESIn5sKp2YL2MU9le4NeUoWywXj2rNl9Z37pzpqZE0EgXs4wy42vlk78+G5mcsjMuKDh084XZmEqsI9W0lCh7s1CANzW2TQOf8TYZOp5cPirQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
